### ISSUE TITLE
custom validation 

### ISSUE THREAD

**Issue by stuart-thackray** [nitrogen/nitrogen_core#104]
Hi, 

I have been having a problem with the custom validators; it may not be something allowed or catered. I am bit lost where to look or what might be causing.

I have module lets say index.erl; that has a button and that button calls other module(s) to get the elements to output, which are added to the page via a wf:replace

 The validators are then set via a comet otherwise I get "livevalidation.min.js:1 Uncaught Error: LiveValidation::initialize - No element reference or element id has been provided!"

there is a 1 second delay on the comet then the validators are wired and flush called. 

The built in validators such as #is_required{} work as expected however the custom validators never seem to fire. 

I have a sample of the files (index.erl & dynamic_elements_render.erl) in https://drive.google.com/file/d/0B0_ahQMa6SwjT0JYbnRudFhyUzQ/view

**Comment by choptastic** [comment]
Hard to say exactly, but the error mentioned is almost always related to
trying to wire a validator to an element that either 1) does not exist yet,
or 2) was removed from the page.

The short of it is that Livevalidation is trying to add something to an
element that doesn't exist.

The most common  fix for this is to make sure you wire your validators with
wf:defer instead of wf:wire. Defer will ensure that the elements were added
to the page before the validators are trying to be wired.

--
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by stuart-thackray** [comment]
Hi Jesse, 

that error I mentioned was more trying to explain why i was wiring the validators via a comment pool. 

My actual problem is that the built in validators work when wired in such a way; however the custom validators don't. 

I will try the suggestion of wiring using defer thanks for the suggestion.

**Comment by stuart-thackray** [comment]
Thank you very much Jesse, defer and not trying to wire custom validators in comet pools was the answer.

**Comment by choptastic** [comment]
Interesting that the custom validators didn't work when wired from a comet
pool.  Thanks for the heads up.  This is definitely something that needs to
be fixed.

I've got a plan to completely rework the validation system, and remove
LiveValidation altogether. It's a little too fragile for my tastes, and I
don't see why we can't do it almost completely with vanilla nitrogen.

-Jesse

On Wed, Apr 6, 2016 at 11:35 AM, stuart-thackray <notifications@github.com>
wrote:

> Thank you very much Jesse, defer and not trying to wire custom validators
> in comet pools was the answer.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/nitrogen/nitrogen_core/issues/104#issuecomment-206453642>
>



-- 
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by stuart-thackray** [comment]
It makes sense now though; I think custom validators a fun but the comet dies so I am not sure if the fun is valid. 

Thank you very much again for another answer to something that was stumping me :)
